version: '3'

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - VK_API_TOKEN=${VK_API_TOKEN}
    depends_on:
      - db
  db:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=poems-notificator

